# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='allow_script',
            new_name='use_script',
        ),
    ]
