# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20170519_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('use_script', 'Can insert Javascript into posts'),)},
        ),
    ]
